### ISSUE TITLE
API

### ISSUE THREAD

**Issue by lauvetech** [luke-chang/js-spatial-navigation#11]
Hi, i tried to remove a element from being navigable using SpatialNavigation.remove("selector") but it doesnt seem to work at all. If i pause the nav though, that works but i just wanna remove and element from being navigable for a while.

**Comment by luke-chang** [comment]
Hi, @lauvetech,

`SpatialNavigation.remove()` is used for removing a section added previously by `SpatialNavigation.add()`. It is not able to remove a specific element from the current section's definition.

However, there are several ways to achieve your goal:

- Assign a callback function to `navigableFilter` and `return false` on specific elements when you need.
- Assign an exclusive selector, e.g. assign `'.navigable:not(.disabled)'` and toggle `disabled` class when needed. 
- Update the `selector` of the section by `SpatialNavigation.set()` according to the up-to-date navigable element set.

Hope it helps.
