### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by logixoul** [luke-chang/js-spatial-navigation#12]
Hi.
I'd like to know which version of the Mozilla Public License this project is licensed under. (there are several)

Cheers!

**Comment by logixoul** [comment]
Ah, I just found out by looking at the LICENSE file. Would be nice to specify the version at the end of README.md as well, though.

**Comment by luke-chang** [comment]
Thanks for the reminder. Will update it soon in the next patch.

**Comment by luke-chang** [comment]
Updated.
