### ISSUE TITLE
How to check the current focused Element is the last element

### ISSUE THREAD

**Issue by nickcartery** [luke-chang/js-spatial-navigation#17]
Hi Luke,

How can I check the current element is the last item? I want to remove all focusable class in the list TV and add new focusable class to the left menu and reinitialize for this menu?

Take a look at my site plz: http://tv.beeb.vn

Thanks!

**Comment by luke-chang** [comment]
Hi,

I'm not quite sure your scenario. What did you mean the last item? Is it the item that no more items in its down direction?

**Comment by nickcartery** [comment]
`Is it the item that no more items in its down direction?`
Yes :D All 4 direction, I want to check if the current item is at the end or the beginning of row, and focus to new area

**Comment by luke-chang** [comment]
You can listen to [`sn:navigatefailed`](https://github.com/luke-chang/js-spatial-navigation#snnavigatefailed) event. It's filed when nothing happens after pressing arrow keys.

Note that you might want to set [`straightOnly`](https://github.com/luke-chang/js-spatial-navigation#straightonly) to prevent the focus from moving to elements in the oblique directions.
