### ISSUE TITLE
Allow navigation with Mousewheel too

### ISSUE THREAD

**Issue by onigetoc** [luke-chang/js-spatial-navigation#21]
How can i implement and add mousewheel navigation with spatial navigation?
May be with this jQuery plugin
https://plugins.jquery.com/mousewheel/
https://stackoverflow.com/questions/29652911/catch-mousewheel-up-or-down-with-jquery-js-without-actually-scrolling/29656088#29656088

**Comment by luke-chang** [comment]
Yeah, it's a good option. Maybe you can do something like:

```js
$(window).mousewheel(function(turn, delta) {
  if (delta == 1) {
    SpatialNavigation.move("down");
  } else {
    SpatialNavigation.move("up");
  }
  return false;
});
```

**Comment by onigetoc** [comment]
Thank you, this is exactly what i did yesterday and it's working.
Mousewheel + Sound navigation.
Far from perfect, i will try to center focused element on overflow.
http://tvcast.top/scripts/js-spatial-navigation-master/demo/3.2_like_youtube_tv-mousewheel.html

**Comment by luke-chang** [comment]
Good to know it works. :)
