### ISSUE TITLE
NPM metadata claims license is ISC (is actually MPL-2.0)

### ISSUE THREAD

**Issue by ajorg-aws** [luke-chang/js-spatial-navigation#42]
The NPM metadata at https://www.npmjs.com/package/spatial-navigation-js claims the license is ISC (which is a very permissive license) but the project actually has an MPL-2.0 (copyleft) license. Can you update one or the other so that they are consistent?

**Comment by luke-chang** [comment]
Thanks for reporting this. However, the NPM package wasn't published by me (and I don't event know it.) I would suggest not depending on it in your project.

**Comment by ajorg-aws** [comment]
Thanks!
