### ISSUE TITLE
Issue while using in my application

### ISSUE THREAD

**Issue by praveenupadhyay997** [luke-chang/js-spatial-navigation#45]
1. What are the minimum versions of angular,Npm,gulp & zone.js version required to run the spatial navigation? Currently our angular version was 4 and npm version was 7.10.

2. I need to upgrade my angular application for that specific version of various DLL dependencies which i need to modify in package.json file.How can i get exact dll version of various dependencies. Also which all files I need to take for the same.

3. Currently if anything is added as an external file in our application the files get automatically deleted. Can you suggest the reason behind this?

**Comment by praveenupadhyay997** [comment]
I found solution for the above. Thanks Luke chang for an amazing library.

**Comment by antoinecharlet** [comment]
Hey ! Can you share this solution plz  ? 😀 thanks in advance

**Comment by praveenupadhyay997** [comment]
Use node module installation process. Do let me know if this helps. In case you can mention your use case then I might help you better.
